
trigger:
- main
pool:
  name: Default
  demands:
  - agent.name -equals DESKTOP-LV6N60A

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.15.0'
  displayName: 'Install Node.js'

# Cache node_modules
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | package-lock.json'
    path: '$(Pipeline.Workspace)/node_modules'
    restoreKeys: |
      npm | "$(Agent.OS)"
  displayName: 'Cache node_modules'

- script: |
    npm install
  displayName: 'Install dependencies'

# Cache Next.js build cache
- task: Cache@2
  inputs:
    key: 'nextjs | "$(Agent.OS)" | .next/cache'
    path: '.next/cache'
    restoreKeys: |
      nextjs | "$(Agent.OS)"
  displayName: 'Cache Next.js build cache'

- script: |
    npm run build
  displayName: 'Build project'

- script: |
    npm run lint
  displayName: 'Run lint'
