trigger:
- main

pool:
  name: Default
  demands:
  - agent.name -equals DESKTOP-LV6N60A



steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.15.0'
  displayName: 'Install Node.js'

- script: |
    echo "MONGODB_URI is set." # Note: This will not print the actual value due to secret masking
  displayName: 'Print MongoDB URI'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run lint
  displayName: 'Run lint'

- script: |
    npm run start-scheduler
  displayName: 'Run scheduler script'
