
trigger:
- main
pool:
  name: Default
  demands:
  - agent.name -equals DESKTOP-LV6N60A

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run build
  displayName: 'Build project'
