trigger:
- main

pool:
  name: Default
  demands:
  - agent.name -equals DESKTOP-LV6N60A

variables:
  - name: MONGODB_URI
    value: $(MONGODB_URI) # Ensure this is set correctly in the pipeline settings

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.15.0'
  displayName: 'Install Node.js'

- script: |
    echo "MONGODB_URI is: $(MONGODB_URI)" # This step will print the MongoDB URI for debugging
  displayName: 'Print MongoDB URI'

- script: |
    npm install # Install dependencies
  displayName: 'Install dependencies'

- script: |
    npm run lint # Run lint checks
  displayName: 'Run lint'

# Add the scheduler script step
- script: |
    npm run start-scheduler # Run the scheduler script
  displayName: 'Run scheduler script'
