trigger:
- main

pool:
  name: Default
  demands:
  - agent.name -equals DESKTOP-LV6N60A

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.15.0'
  displayName: 'Install Node.js'







# Cache Next.js build cache
- task: Cache@2
  displayName: 'Cache .next/cache'
  inputs:
    key: 'next | $(Agent.OS) | package-lock.json'
    path: '$(System.DefaultWorkingDirectory)/.next/cache'
    restoreKeys: |
      next | $(Agent.OS)

- script: |
    npm install
  displayName: 'Install dependencies'
- script: |
    npm run build
  displayName: 'Build project'
- script: |
    npm run start-scheduler
  displayName: 'Run start-scheduler'
- script: |
    npm run lint
  displayName: 'Run lint'
